import { Inter, Montserrat, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// const roboto = Roboto({ subsets: ["latin"], weights: [400] });


const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

const roboto = Roboto({ subsets: ["latin"],  weight: ["100", "300", "400", "500", "900"] });
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}


export {roboto, inter, montserrat}