import { Inter, Montserrat, Roboto, Quicksand } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
// const roboto = Roboto({ subsets: ["latin"], weights: [400] });

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "900"],
});
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const quicksand = Quicksand({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
          <div className="md:hidden">{children}</div>
          <div className="hidden md:block">
            <div className="min-h-screen flex items-center justify-center text-xl font-bold">

            The design is avilable for mobile devices only
            </div>
            
            </div>
        </Providers>
      </body>
    </html>
  );
}

export { roboto, inter, montserrat, quicksand };
